import { PlatformColor } from 'react-native';

const APP_BACKGROUND_PRIMARY = PlatformColor('APP_BACKGROUND_PRIMARY');
const FONT_PRIMARY_COLOR = PlatformColor('FONT_PRIMARY_COLOR');
const FONT_PRIMARY_COLOR_INVERTED = PlatformColor(
  'FONT_PRIMARY_COLOR_INVERTED',
);
const FONT_SECONDARY_COLOR = PlatformColor('FONT_SECONDARY_COLOR');
const FONT_COLOR_FADED = PlatformColor('FONT_COLOR_FADED');
const ELEMENT_FADE_OR_BACKGROUND = PlatformColor('ELEMENT_FADE_OR_BACKGROUND');
const ELEMENT_FADE_OR_BACKGROUND_DARKER = PlatformColor(
  'ELEMENT_FADE_OR_BACKGROUND_DARKER',
);
const ELEMENT_FADE_OR_BACKGROUND_LIGHTER = PlatformColor(
  'ELEMENT_FADE_OR_BACKGROUND_LIGHTER',
);
const ACCENT_COLOR_LIGHTER = PlatformColor('ACCENT_COLOR_LIGHTER');
const ACCENT_COLOR_DARKER = PlatformColor('ACCENT_COLOR_DARKER');
const SUNSET_ORANGE = PlatformColor('SUNSET_ORANGE');
const OVERLAY = PlatformColor('OVERLAY');

export const ColorsIOS = {
  APP_BACKGROUND_PRIMARY,
  FONT_PRIMARY_COLOR,
  FONT_PRIMARY_COLOR_INVERTED,
  FONT_SECONDARY_COLOR,
  FONT_COLOR_FADED,
  ELEMENT_FADE_OR_BACKGROUND,
  ELEMENT_FADE_OR_BACKGROUND_DARKER,
  ELEMENT_FADE_OR_BACKGROUND_LIGHTER,
  ACCENT_COLOR_LIGHTER,
  ACCENT_COLOR_DARKER,
  SUNSET_ORANGE,
  OVERLAY,
};
