export enum ColorsDark {
  APP_BACKGROUND_PRIMARY = '#202124',
  FONT_PRIMARY_COLOR = 'white',
  FONT_PRIMARY_COLOR_INVERTED = '#363535',
  FONT_SECONDARY_COLOR = 'white',
  FONT_COLOR_FADED = 'grey',
  ELEMENT_FADE_OR_BACKGROUND = '#323236',
  ELEMENT_FADE_OR_BACKGROUND_DARKER = '#21212b',
  ELEMENT_FADE_OR_BACKGROUND_LIGHTER = '#424146',
  ACCENT_COLOR_LIGHTER = '#4F378B',
  ACCENT_COLOR_DARKER = '#1a1921',
  MAIN_BUTTON_COLOR = '#4F378B',
  MAIN_BUTTON_TEXT_COLOR = 'white',
  SUNSET_ORANGE = '#ef5350',
}

export enum ColorsLight {
  APP_BACKGROUND_PRIMARY = '#f0f0f3',
  FONT_PRIMARY_COLOR = '#363535',
  FONT_PRIMARY_COLOR_INVERTED = 'white',
  FONT_SECONDARY_COLOR = '#fafcfe',
  FONT_COLOR_FADED = 'grey',
  ELEMENT_FADE_OR_BACKGROUND = '#E1E1E3',
  ELEMENT_FADE_OR_BACKGROUND_DARKER = '#DADAE1',
  ELEMENT_FADE_OR_BACKGROUND_LIGHTER = '#D3D3D5',
  ACCENT_COLOR_LIGHTER = '#1a73e8',
  ACCENT_COLOR_DARKER = '#e9e9f0',
  MAIN_BUTTON_COLOR = '#1a73e8',
  MAIN_BUTTON_TEXT_COLOR = '#fafcfe',
  SUNSET_ORANGE = '#ef5350',
}

export const THEME_COLORS = {
  light: ColorsLight,
  dark: ColorsDark,
};

export type Theme = typeof ColorsDark | typeof ColorsLight;
