name: Deploy-Android-PROD
on:
  push:
    branches:
      - master
      - "release/**"

env:
  APP_CENTER_USER_TOKEN: ${{ secrets.APP_CENTER_USER_TOKEN }}
  APP_NAME: ${{ 'Fancy-converter/Converter_PROD' }}
  TESTING_GROUP: ${{ 'ENV_PROD' }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/release/app-release.apk' }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo workspace dir
        run: echo $GITHUB_WORKSPACE ls
        shell: bash

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install dependencies
        run: npm install --force

      - name: Install appcenter cli
        run: npm install -g appcenter-cli

      - name: Copy the key file to the signing key file
        run: echo "${{ env.KEYSTORE }}" | base64 -d > $GITHUB_WORKSPACE/release-key.keystore
        shell: bash

      - name: Build Signed APK
        run: cd android && chmod +x ./gradlew && ./gradlew assembleRelease -PKEYSTORE=$GITHUB_WORKSPACE/release-key.keystore -PKEYSTORE_PASSWORD=${{ env.KEYSTORE_PASSWORD }} -PKEY_ALIAS_PASSWORD=${{ env.KEY_ALIAS_PASSWORD }} -PKEY_ALIAS=${{ env.KEY_ALIAS }}

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: android-release
      #     path: ${{ env.UPLOAD_FILE }}

      - name: Distribute apk to App Center
        uses: akiojin/appcenter-distribute-github-action@v1
        with:
          token: ${{ secrets.APP_CENTER_USER_TOKEN }}
          path: ${{ env.UPLOAD_FILE }}
          app: ${{ env.APP_NAME }}
          group: Collaborators
