name: Deploy-Android-PROD
on:
  pull_request:
    branches:  
      - master
      - 'releases/**'
  push:
    branches: 
      - test

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_CONVERTER_ANDROID_PROD }}
  APP_NAME: ${{ 'Fancy-converter/ENV_PROP' }}
  TESTING_GROUP: ${{ 'ENV_PROD' }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: npm install

      - name: Build Signed APK
        run: cd android && ./gradlew assembleDebug --stacktrace -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
        uses: victorbnl/build-signed-apk@v1.0.0
        with:
          keystore_b64: ${{ secrets.keystore }}
          keystore_password: ${{ secrets.keystore_password }}
          key_alias: ${{ secrets.key_alias }}
          key_password: ${{ secrets.key_password }}
        
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.ENV_PROD }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
          