name: Deploy-Android-PROD
on:
  pull_request:
    branches:  
      - master
      - 'releases/**'
  push:
    branches: 
      - test

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_CONVERTER_ANDROID_PROD }}
  APP_NAME: ${{ ‘Fancy-converter/ENV_PROD’ }}
  TESTING_GROUP: ${{ ‘ENV_PROD’ }}
  UPLOAD_FILE: ${{ ‘android/app/build/outputs/apk/app-release.apk' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: npm run cd android && ./gradlew assembleRelease
        
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.ENV_PROD }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
          