name: TS lint check
on:
  pull_request:
    branches:
      - master
      - "releases/**"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo workspace dir
        run: echo $GITHUB_WORKSPACE ls
        shell: bash

      - name: Install dependencies
        run: npm install --force

      - name: Run lint check
        run: npm run lint

      - name: Run TS check
        run: npm run type:check
